#!/bin/bash

help() {
  echo "Usage:"
  echo "  zpackage cd <package_name>"
}

core() {
  if [ "$1" = "" ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi
  
  local package_name=$1
  if [ -z "${package_name}" ]; then
    log::error "package name is required"
    exit 1
  fi

  local package_path=$(package::get_path $package_name)
  if [ ! -d "$package_path" ]; then
    log::error "[$(timestamp)][package][cd] package($package_name) not found"
    exit 1
  fi

  cd $package_path
  exec $SHELL
}

run() {
  core $@
}

run $@
