#!/bin/bash

help() {
  echo "Usage:"
  echo "  zpackage list"
  echo ""
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  zpackage_list
}

run() {
  core $@
}

run $@
