#!/bin/bash

help() {
  echo "Usage:"
  echo "  zpackage version <package>"
  echo ""
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi
  
  local name=$1
  if [ -z "$name" ]; then
    log::error "package name is requried"
    exit 1
  fi

  package::version $name
}

run() {
  core $@
}

run $@
