#!/bin/bash

package::config() {
  local name=$1
  if [ -z "$name" ]; then
    log::error "[$(timestamp)][package::config] name is required"
    return 1
  fi

  local package_config_path=$(package::get_config_path $name)
  if [ ! -f $package_config_path ]; then
    log::error "[$(timestamp)][package::load_config] package config file not found: $package_config_path"
    return 1
  fi

  cat $package_config_path
}

export -f package::config
