#!/bin/bash

package::info() {
  local name=$1
  if [ -z "$name" ]; then
    log::error "[$(timestamp)][package::info] name is required"
    return 1
  fi

  local package_mod_path=$(package::get_mod_path $name)
  if [ ! -f $package_mod_path ]; then
    log::error "[$(timestamp)][package::load_mod] package mod file not found: $package_mod_path"
    return 1
  fi

  cat $package_mod_path
  echo ""
  package::version_with_git_info $name
}

export -f package::info
