#!/bin/bash

package::version() {
  local name=$1
  if [ -z "$name" ]; then
    log::error "[$(timestamp)][package::version] name is required"
    exit 1
  fi

  # @TODO
  if [ ! -f "$(package::get_mod_path $name)" ]; then
    echo "-"
    return
  fi

  package::load_mod $name
  echo $VERSION
}

package::version_with_git_info() {
  local name=$1
  if [ -z "$name" ]; then
    log::error "[$(timestamp)][package::version_with_git_info] name is required"
    return 1
  fi

  local version=$(package::version $name)

  local package_path=$(package::get_path $name)
  if [ ! -d "$package_path" ]; then
    log::error "[$(timestamp)][package::load_mod] package not found: $name"
    return 1
  fi

  if [ ! -d "$package_path/.git" ]; then
    log::error "[$(timestamp)][package::load_mod] package is not a git repository: $name"
    return 1
  fi

  cd $package_path
  local gittimestamp=$(git::commit_timestamp)
  local githash=$(git::commit_hash)

  echo "$version($githash $gittimestamp)"
}

export -f package::version
export -f package::version_with_git_info
