#!/bin/bash

LIMA_VERSION=v0.6.4

help() {
  echo "Usage:"
  echo "  zmicro package install lima <args...>"
  echo ""
}

install() {
  if [ "$(os_is_macos)" = "true" ]; then
    pm install lima
    return
  fi

  local tmp_file=/tmp/lima.tar.gz
  local url=https://github.com/lima-vm/lima/releases/download/${LIMA_VERSION}/lima-${LIMA_VERSION:1}-Linux-x86_64.tar.gz
  curl -fSL $url -o $tmp_file
  cd /tmp
  tar -zxvf $tmp_file >>/dev/null 2>&1
  rm $tmp_file
  #
  sudo mv bin/* /usr/local/bin
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  install

  log_success "install lima success."
}

run() {
  core $@
}

run $@
